jenkins:
  hosts:
    85.224.31.13
  vars:
    domain: site.dev
    web_user: www-data
    web_group: www-data
    ansible_user: ansible
    ansible_become: True
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
