jenkins:
  hosts:
    51.116.187.58
  vars:
    domain: site.dev
    web_user: www-data
    web_group: www-data
    ansible_user: jenkins
    ansible_become: True
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
