web:
    hosts:
      192.168.1.151
      vars:
        doamin: site.dev
        web_user: www.data
        web_group: www.data
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_sudo_pass: ubuntu

        