jenkins:
  hosts:
    127.0.0.1
  vars:
    domain: site.dev
    web_user: www-data
    web_group: www-data
    ansible_user: jonny
    ansible_become: True
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
